### ISSUE TITLE
Update `openmobilehub.com` References in `android-omh-maps` Documentation

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/android-omh-maps#113]
Please replace all instances of `openmobilehub.com` in the `android-omh-maps` repository documentation with the correct domain or updated URLs.

**References**:
- [Search results for `openmobilehub.com` in `android-omh-maps`](https://github.com/search?q=repo%3Aopenmobilehub%2Fandroid-omh-maps%20openmobilehub.com&type=code)

**Tasks**:
1. Identify and replace all occurrences of `openmobilehub.com` in the documentation.
2. Verify that the updated links are accurate and functional.

This ensures users are directed to the most current resources.

**Comment by adamTrz** [comment]
Hi @dzuluaga 
I think all references are correct? Could you please guide me which links should be replaced?

**Comment by dzuluaga** [comment]
Sure, @adamTrz. Please take a look at the search results linked above.

**Comment by adamTrz** [comment]
> Sure, @adamTrz. Please take a look at the search results linked above.

Ahh apologies for that! My VSCode make a trick on me and search results were broken 🙈 

All should be fixed with https://github.com/openmobilehub/android-omh-maps/pull/114
