### ISSUE TITLE
Time to Update Our README GIFs with the Latest Features!

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/android-omh-maps#58]
Hey Team,

I've noticed that the animated GIFs in our README for the Android OMH Maps project are a bit behind the times. They're still showcasing the app from the OMH 1.0 days, focusing solely on Google Maps and OpenStreetMap.

We've made some awesome enhancements since then, expanding our support to include not just the original Google Maps and OSM, but also bringing Microsoft Azure and Mapbox into the mix. It's pretty important for our README to reflect these updates, especially with our open-source schedule looking busy for the week of April 15th. We want to make sure developers get a real taste of what the latest OMH version can do right from the start.

@Nataliagros and @artus9033, could we get those GIFs updated? It’d be fantastic to showcase the breadth of our current features and give everyone a proper peek at the latest and greatest in OMH.

Thanks!

CC - @prestonlau

**Comment by dzuluaga** [comment]
Thanks for the quick turnaround on these changes, Dominik. Could you please ensure that the animations have transparent backgrounds? The first impression is crucial, and this detail would help a lot. I really appreciate your efforts!

**Comment by Nataliagros** [comment]
Hi @dzuluaga preparing animations with no background would require a lot of additional effort from our developers. How important is that part for you? Should we plan to prepare them or are they acceptable in this form as well?

**Comment by ddolny** [comment]
Sure, I was working on it today, tomorrow I'll finish updating gifs on both projects - maps and auth. All animations will have edge-to-edge design, with transparent background. Also StatusBar will have the same color as the AppBar.

**Comment by dzuluaga** [comment]
Thank you, Dominik, for addressing these issues. The screenshot of the map looks very clean.

I’ve added some notes to the Auth repo issue to explore if we might clean up the back corners in a similar manner to what you’ve achieved here. I appreciate your attention to detail!
