### ISSUE TITLE
Separate Documentation Publishing Workflow for Increased Efficiency

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/android-omh-maps#64]
Hello Natalia, Adam, and Artur,

We've noticed that our current GitHub Actions workflow, as defined in `on_push_workflow.yml`, combines multiple tasks such as publishing to Maven, managing snapshots, and building documentation, all triggered by a single push event. This setup is causing inefficiencies, particularly around documentation updates. 

Currently, any minor change to the documentation requires triggering the entire pipeline, which is not only resource-intensive but also slows down the process of updating and iterating on the documentation. This is particularly cumbersome for both our team and external teams who need to work swiftly on documentation.

**Suggested Change:**
I propose we create a separate workflow specifically for documentation updates. This workflow would be independent of the current pipeline but could still be triggered by push events to relevant branches or directories (e.g., any changes within the `docs/` directory).

**Benefits:**
1. **Faster Iteration on Documentation:** Changes can be published quickly without waiting for unrelated CI tasks to complete.
2. **Reduced Resource Consumption:** By isolating documentation tasks, we use fewer CI resources.
3. **Better Organization:** Separating concerns by having distinct workflows for different tasks improves maintainability and scalability of our CI/CD setup.

**Extracted Workflow Section for Reference:**
```yaml
  build-documentation:
    needs: auth-plugins-local
    name: Build documentation
    runs-on: ubuntu-latest
    # (Include all related steps and configurations here)
```

Please consider this suggestion as it could significantly enhance our development workflow efficiency, especially for documentation.

Thank you!

CC - @prestonlau

**Comment by kubaluberadzki** [comment]
Thanks Diego, good call, we will bring it up with the team and improve on in the next iteration @Nataliagros. Totally agree that we should have the ability to update documentation independently. However there's always the concern of docs/app being out of sync with separate workflows?

**Comment by dzuluaga** [comment]
Thank you for considering my suggestion, Kuba. Regarding your concern about the documentation and application potentially being out of sync when using separate workflows, one effective solution could be to utilize the `workflow_run` event in GitHub Actions. This approach would allow you to automatically trigger the documentation generation and publishing process once the primary application deployment workflow has successfully completed. Here's an example configuration:

```yaml
name: Publish Docs
on:
  workflow_run:
    workflows: ["on_push_workflow"]
    types:
      - completed
...
```

This setup ensures that updates to the documentation are only made after the application updates are deployed, keeping them in sync. If you're looking for more control or have specific integration needs, we can also explore more complex options like repository dispatch, which I'm open to discussing further.

**Comment by ddolny** [comment]
Hi, I've prepared new PR with this issue resolved:
https://github.com/openmobilehub/android-omh-maps/pull/76
