### ISSUE TITLE
Update Documentation Links in README.md to Point to HTML Pages Instead of Markdown Files

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/android-omh-maps#65]
The current links in the `README.md` file of the `android-omh-maps` repository point directly to Markdown files within the repository, rather than to the Jekyll-generated HTML documentation pages. This approach is inconsistent with how documentation links are handled in the OMH Auth project, which points to HTML pages.

## Affected Links
Currently, the documentation section of the README includes links that point directly to the Markdown files in the repository:
- [Core Package documentation](/packages/core/README.md)
- [Google Maps Plugin documentation](/packages/plugin-googlemaps/README.md)
- [OpenStreetMap Plugin documentation](/packages/plugin-openstreetmap/README.md)
- [Azure Maps Plugin documentation](/packages/plugin-azuremaps/README.md)

These should instead link to the corresponding HTML pages generated by Jekyll, similar to the [API Reference Docs](https://openmobilehub.github.io/omh-maps) link.

## Proposed Changes
Update the README.md file to replace links to the Markdown files with links to the appropriate HTML pages. If the HTML pages do not currently exist, they should be generated or confirmed to align with the structure used in the OMH Auth project.

Thank you.

**Comment by artus9033** [comment]
Thank you @dzuluaga , once 0ed1bf1 is merged, we will have the links updated to point to the docs deployment domain.
