### ISSUE TITLE
Error Obtaining ID Token in Build and Publish Documentation Workflow

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/android-omh-maps#79]
Same issue as in https://github.com/openmobilehub/android-omh-auth/issues/72.

Link to the Failed Job:
[Failed Job Log](https://github.com/openmobilehub/android-omh-maps/actions/runs/8823701818)

Please address the deprecation warning `Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/upload-artifact@v3. ` by bumping it up to v3. Thanks. Please apply this to Auth.

**Comment by adamTrz** [comment]
Hey @dzuluaga - mind checking it again please? :)

**Comment by dzuluaga** [comment]
It's working now. Thank you, Dominik and Adam!
