### ISSUE TITLE
Update API Documentation Link in README.md

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/android-omh-maps#83]
The link in the README.md file for `openmobilehub/android-omh-maps` should be updated to direct users to version 2.0 of the OMH Maps API documentation (`https://www.openmobilehub.com/android-omh-maps/api-docs/`) instead of version 1.0 (`https://openmobilehub.github.io/omh-maps`). Please fix this to ensure users are directed to the correct documentation.

**Comment by dzuluaga** [comment]
Thanks @ddolny. Could you please also regenerate the docs to fix this issue? E.g. https://www.openmobilehub.com/android-omh-maps/api-docs/ still points to OMH 1.0.

**Comment by ddolny** [comment]
Sure, as soon as PRs will be merged, I will run workflow to generate docs
