### ISSUE TITLE
Implement Workflow for Generating Sample App APKs and Enabling Direct Testing from GitHub

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/android-omh-maps#85]
Same as https://github.com/openmobilehub/android-omh-auth/issues/77. Thanks for looking into it.

**Comment by dzuluaga** [comment]
Friendly ping.

**Comment by dzuluaga** [comment]
Hi @Nataliagros,

As discussed, credentials should not be a blocker for integrating this into the CI/CD. The team will use environment variables with placeholder dummy values and set up the process to release builds into GH Releases. We will update the environment variables with valid values soon.

Thank you!

**Comment by andrei-zgirvaci** [comment]
Hey @dzuluaga, thanks for bringing this to our attention! This was addressed and should be fixed in https://github.com/openmobilehub/android-omh-maps/pull/110/commits/f40178f3722155381c19374d7d756aa2eacb3470.
